const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },

  title:     { type: String, required: true, trim: true },
  completed:  { type: Boolean, default: false },
  priority:  { type: String, enum: ['high', 'medium', 'low'], default: 'medium' },
  category:  { type: String, enum: ['personal', 'work', 'study', 'health', 'other'], default: 'personal' },
  dueDate:   { type: Date, default: null },

  // NEW — exact time task was marked complete
  completedAt: { type: Date, default: null },

  // NEW — total minutes spent focusing on this task
  focusMinutes: { type: Number, default: 0 },

  // NEW — tags for smart suggestions
  tags: [{ type: String }],

  // NEW — task was generated by AI suggestion
  isAISuggested: { type: Boolean, default: false }

}, { timestamps: true });

module.exports = mongoose.model('Task', taskSchema);